# Useful links to make your chat even more beautiful:
# MiniMessages Format doc: https://docs.adventure.kyori.net/minimessage#format
# MiniMessages WebUI: https://webui.adventure.kyori.net/
# PAPI Placeholders: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders

# Channel name can be modified
# Channel format can be modified with PAPI's placeholders and MiniMessage syntax.
# MiniMessage syntax is powerful, you can format and add hover/click events easily!
# Channel command can be modified but you'll need to restart your server to get the changes.

# You can define custom templates in the section below
# and be used them in channel formats like so: <TEMPLATE NAME> !
channels:
    global:
        name: "Global Chat"
        format: "<town><nation><rank> <username> > <message>"
        command: "gc"

    town:
        name: "Town Chat"
        format: "<town_prefix> <rank> <username> <aqua>> <message>"
        spy_format: "<spy_prefix> <town_prefix> <town> <username> <dark_purple>> <message>"
        command: "tc"

    nation:
        name: "Nation Chat"
        format: "<nation_prefix> <town><rank> <username> <gold>> <message>"
        spy_format: "<spy_prefix> <nation_prefix> <nation> <username> <purple>> <message>"
        command: "nc"

# You can use PAPI's placeholders and MiniMessage syntax here too!
templates:
    town_prefix: "<aqua><bold>TC</bold></aqua>"
    nation_prefix: "<gold><bold>NC</bold></gold>"
    spy_prefix: "<dark_purple><bold>SPY</bold></dark_purple>"

    rank: "%townyadvanced_towny_colour%%townyadvanced_player_status%"

    username: "%townyadvanced_towny_colour%%player_name%"

    town: "<hover:show_text:'%townyadvanced_town_formatted%\n%townyadvanced_town_residents_amount% resident.s'>%townyadvanced_town_tag%</hover>"

    nation: "<hover:show_text:'%townyadvanced_nation_formatted%\n%townyadvanced_nation_residents_amount% resident.s'>%townyadvanced_nation_tag%</hover>"

lang:
    channel_switched: "Switched to <channel>"
    disabled: "Disabled"
    enabled: "Enabled"
    # Status is either disabled or enabled ^
    channel_toggled: "<status> <channel>"
    spying_toggled: "Spying is <status>"
    err_channel_not_found: "Channel <channel> not found"
    err_sender_not_player: "<red>You need to be in-game in order to do this!"
    err_channel_disabled: "You disabled this channel! Use /<channel> toggle chat to enable it"

blacklist:
    - "chocolatine"
    - "fuck"
    - "shit"

# MiniMessage, Placeholders and Templates can be used here
misc:
    join_message: "<green>→</green> <rank> <username>"
    quit_message: "<red>←</red> <rank> <username>"
    advancement:
        # <advancement_title> and <advancement_description> can be used.
        challenge: "<dark_purple>✽ <username> has made the advancement <bold><hover:show_text:'<dark_purple>a<advancement_description>'><advancement_title>"
        goal: "<gold>✸ <username> has made the advancement <bold><hover:show_text:'<gold>a<advancement_description>'><advancement_title>"
        task: "<yellow>✦ <username> has made the advancement <bold><hover:show_text:'<yellow>a<advancement_description>'><advancement_title>"
