# Useful links to make your chat even more beautiful:
# MiniMessages format: https://docs.adventure.kyori.net/minimessage#format
# MiniMessages viewer: https://webui.adventure.kyori.net/
# PAPI placeholders: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders
# Towny placeholders: https://github.com/TownyAdvanced/Towny/wiki/Placeholders
# Note: PAPI placeholders need to be used like so : <papi:my_placeholder>

# Channel name can be modified
# Channel format can be modified with PAPI's placeholders and MiniMessage syntax.
# MiniMessage syntax is powerful, you can format and add hover/click events easily!
# Channel command can be modified but you'll need to restart your server to get the changes.

# You can define custom tags in the section below
# and use them in channel formats like so: <TAG_NAME> !
channels:
    global:
        name: "Global Chat"
        format: "<town><nation><rank> <username> > <message>"
        command: "gc"

    town:
        name: "Town Chat"
        format: "<town_prefix> <rank> <username> <aqua>> <message>"
        spy_format: "<spy_prefix> <town_prefix> <town> <username> <dark_purple>> <message>"
        command: "tc"

    nation:
        name: "Nation Chat"
        format: "<nation_prefix> <town><rank> <username> <gold>> <message>"
        spy_format: "<spy_prefix> <nation_prefix> <nation> <username> <purple>> <message>"
        command: "nc"

# You can use PAPI's placeholders and MiniMessage syntax here too!
tags:
    town_prefix: "<aqua><bold>TC</bold></aqua>"
    nation_prefix: "<gold><bold>NC</bold></gold>"
    spy_prefix: "<dark_purple><bold>SPY</bold></dark_purple>"

    rank: "<papi:townyadvanced_towny_colour><papi:townyadvanced_player_status>"

    username: "<papi:townyadvanced_towny_colour><papi:player_name>"

    town: "<hover:show_text:'<papi:townyadvanced_town_formatted>\n<papi:townyadvanced_town_residents_amount> resident.s'><papi:townyadvanced_town_tag></hover>"

    nation: "<hover:show_text:'<townyadvanced_nation_formatted>\n<townyadvanced_nation_residents_amount> resident.s'><papi:townyadvanced_nation_tag></hover>"

lang:
    channel_switched: "Switched to <channel>"
    disabled: "Disabled"
    enabled: "Enabled"
    # Status is either disabled or enabled ^
    channel_toggled: "<status> <channel>"
    spying_toggled: "Spying is <status>"
    err_channel_not_found: "Channel <channel> not found"
    err_sender_not_player: "<red>You need to be in-game in order to do this!"
    err_channel_disabled: "You disabled this channel! Use /<channel> toggle chat to enable it"

blacklist:
    - "chocolatine"
    - "fuck"
    - "shit"

# MiniMessage, Placeholders and Tags can be used here
misc:
    join_message: "<green>→</green> <rank> <username>"
    quit_message: "<red>←</red> <rank> <username>"
    advancement:
        # <advancement_title> and <advancement_description> can be used.
        challenge: "<dark_purple>✽ <username> has made the advancement <bold><hover:show_text:'<dark_purple><advancement_description>'><advancement_title>"
        goal: "<gold>✸ <username> has made the advancement <bold><hover:show_text:'<gold><advancement_description>'><advancement_title>"
        task: "<yellow>✦ <username> has made the advancement <bold><hover:show_text:'<yellow><advancement_description>'><advancement_title>"
